
set(PATH_FILE_VERSION_INFO_TEMPLATE ${PATH_FILE_VERSION_INFO}.in)
set(PATH_FILE_VERSION_INFO_COUNTER ${PATH_FILE_VERSION_INFO}.cnt)

function(read_meta param_name default_value input_data)
    string(REGEX MATCH "_META_${param_name}[= \t]+([a-z_A-Z0-9]+)" NULL_STR ${input_data})
    if("${CMAKE_MATCH_COUNT}" STREQUAL "1")
        set(${param_name} ${CMAKE_MATCH_1} PARENT_SCOPE)
    else()
        set(${param_name} ${default_value} PARENT_SCOPE)
    endif()
endfunction()

file(READ ${PATH_FILE_VERSION_INFO_TEMPLATE} FDATA_TEMPLATE)

read_meta(PROJECT_VERSION_MAJOR 1 "${FDATA_TEMPLATE}")
read_meta(PROJECT_VERSION_MINOR 0 "${FDATA_TEMPLATE}")
read_meta(PROJECT_VERSION_PATCH 0 "${FDATA_TEMPLATE}")
read_meta(PROJECT_VERSION_TWEAK 0 "${FDATA_TEMPLATE}")

IF(EXISTS ${PATH_FILE_VERSION_INFO_COUNTER})
    file(READ ${PATH_FILE_VERSION_INFO_COUNTER} CURRENT_VERSION_TWEAK)
    math(EXPR CURRENT_VERSION_TWEAK "${CURRENT_VERSION_TWEAK} + 1")
ELSE()
    set(CURRENT_VERSION_TWEAK "${PROJECT_VERSION_TWEAK}")
ENDIF()
set(PROJECT_VERSION_TWEAK ${CURRENT_VERSION_TWEAK})

file(WRITE ${PATH_FILE_VERSION_INFO_COUNTER} "${CURRENT_VERSION_TWEAK}")
configure_file(${PATH_FILE_VERSION_INFO_TEMPLATE} ${PATH_FILE_VERSION_INFO})
