name: Autobuild Release Assets

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
    contents: write
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cross-compile Windows
        uses: ./.github/actions/cross-compile-win
        with:
          target: version_lib

      - name: Create zip
        run: |
          zip -j BlackSouls2Resize_${{ github.ref_name }}.zip bin/*.dll
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: BlackSouls2Resize_${{ github.ref_name }}.zip
